### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  commentId: T:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  id: R_ServiceUrlSection
  parent: R_BlazorFrontEnd.Configurations
  children:
  - R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
  - R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
  langs:
  - csharp
  - vb
  name: R_ServiceUrlSection
  nameWithType: R_ServiceUrlSection
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  type: Class
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_ServiceUrlSection
    path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
    startLine: 2
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Configurations
  syntax:
    content: 'public class R_ServiceUrlSection : object'
    content.vb: >-
      Public Class R_ServiceUrlSection
          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
  commentId: P:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
  id: ServiceUrlName
  parent: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  langs:
  - csharp
  - vb
  name: ServiceUrlName
  nameWithType: R_ServiceUrlSection.ServiceUrlName
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: ServiceUrlName
    path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
    startLine: 4
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Configurations
  syntax:
    content: public string ServiceUrlName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceUrlName As String
  overload: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
  commentId: P:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
  id: ServiceUrl
  parent: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection
  langs:
  - csharp
  - vb
  name: ServiceUrl
  nameWithType: R_ServiceUrlSection.ServiceUrl
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: ServiceUrl
    path: Library/R_BlazorFrontEnd/Configurations/R_ServiceUrlSection.cs
    startLine: 5
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Configurations
  syntax:
    content: public string ServiceUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceUrl As String
  overload: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: R_BlazorFrontEnd.Configurations
  commentId: N:R_BlazorFrontEnd.Configurations
  name: R_BlazorFrontEnd.Configurations
  nameWithType: R_BlazorFrontEnd.Configurations
  fullName: R_BlazorFrontEnd.Configurations
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  name: ThrowIfNull()
  nameWithType: R_FrontExtensions.ThrowIfNull()
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull()
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  name: ThrowIfNull(Object)
  nameWithType: R_FrontExtensions.ThrowIfNull(Object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName*
  commentId: Overload:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
  name: ServiceUrlName
  nameWithType: R_ServiceUrlSection.ServiceUrlName
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrlName
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl*
  commentId: Overload:R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
  name: ServiceUrl
  nameWithType: R_ServiceUrlSection.ServiceUrl
  fullName: R_BlazorFrontEnd.Configurations.R_ServiceUrlSection.ServiceUrl
