### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Deployment.Models.Package
  commentId: T:R_BlazorFrontEnd.Deployment.Models.Package
  id: Package
  parent: R_BlazorFrontEnd.Deployment.Models
  children:
  - R_BlazorFrontEnd.Deployment.Models.Package.Content
  - R_BlazorFrontEnd.Deployment.Models.Package.FileName
  - R_BlazorFrontEnd.Deployment.Models.Package.IsReference
  langs:
  - csharp
  - vb
  name: Package
  nameWithType: Package
  fullName: R_BlazorFrontEnd.Deployment.Models.Package
  type: Class
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Package
    path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
    startLine: 4
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Deployment.Models
  syntax:
    content: 'public class Package : object'
    content.vb: >-
      Public Class Package
          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: R_BlazorFrontEnd.Deployment.Models.Package.FileName
  commentId: P:R_BlazorFrontEnd.Deployment.Models.Package.FileName
  id: FileName
  parent: R_BlazorFrontEnd.Deployment.Models.Package
  langs:
  - csharp
  - vb
  name: FileName
  nameWithType: Package.FileName
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.FileName
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: FileName
    path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
    startLine: 6
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Deployment.Models
  syntax:
    content: public string FileName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FileName As String
  overload: R_BlazorFrontEnd.Deployment.Models.Package.FileName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_BlazorFrontEnd.Deployment.Models.Package.Content
  commentId: P:R_BlazorFrontEnd.Deployment.Models.Package.Content
  id: Content
  parent: R_BlazorFrontEnd.Deployment.Models.Package
  langs:
  - csharp
  - vb
  name: Content
  nameWithType: Package.Content
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.Content
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Content
    path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
    startLine: 7
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Deployment.Models
  syntax:
    content: public byte[] Content { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property Content As Byte()
  overload: R_BlazorFrontEnd.Deployment.Models.Package.Content*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: R_BlazorFrontEnd.Deployment.Models.Package.IsReference
  commentId: P:R_BlazorFrontEnd.Deployment.Models.Package.IsReference
  id: IsReference
  parent: R_BlazorFrontEnd.Deployment.Models.Package
  langs:
  - csharp
  - vb
  name: IsReference
  nameWithType: Package.IsReference
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.IsReference
  type: Property
  source:
    remote:
      path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: IsReference
    path: Library/R_BlazorFrontEnd/Deployment/Models/Package.cs
    startLine: 8
  assemblies:
  - R_BlazorFrontEnd
  namespace: R_BlazorFrontEnd.Deployment.Models
  syntax:
    content: public bool IsReference { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsReference As Boolean
  overload: R_BlazorFrontEnd.Deployment.Models.Package.IsReference*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: R_BlazorFrontEnd.Deployment.Models
  commentId: N:R_BlazorFrontEnd.Deployment.Models
  name: R_BlazorFrontEnd.Deployment.Models
  nameWithType: R_BlazorFrontEnd.Deployment.Models
  fullName: R_BlazorFrontEnd.Deployment.Models
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  name: ThrowIfNull()
  nameWithType: R_FrontExtensions.ThrowIfNull()
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull()
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  name: ThrowIfNull(Object)
  nameWithType: R_FrontExtensions.ThrowIfNull(Object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
- uid: R_BlazorFrontEnd.Deployment.Models.Package.FileName*
  commentId: Overload:R_BlazorFrontEnd.Deployment.Models.Package.FileName
  name: FileName
  nameWithType: Package.FileName
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.FileName
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: R_BlazorFrontEnd.Deployment.Models.Package.Content*
  commentId: Overload:R_BlazorFrontEnd.Deployment.Models.Package.Content
  name: Content
  nameWithType: Package.Content
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.Content
- uid: System.Byte[]
  isExternal: true
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullName.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: R_BlazorFrontEnd.Deployment.Models.Package.IsReference*
  commentId: Overload:R_BlazorFrontEnd.Deployment.Models.Package.IsReference
  name: IsReference
  nameWithType: Package.IsReference
  fullName: R_BlazorFrontEnd.Deployment.Models.Package.IsReference
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
