### YamlMime:ManagedReference
items:
- uid: R_BlazorDeployment.R_IResult`1
  commentId: T:R_BlazorDeployment.R_IResult`1
  id: R_IResult`1
  parent: R_BlazorDeployment
  children:
  - R_BlazorDeployment.R_IResult`1.Data
  langs:
  - csharp
  - vb
  name: R_IResult<T>
  nameWithType: R_IResult<T>
  fullName: R_BlazorDeployment.R_IResult<T>
  type: Interface
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: R_IResult
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 10
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: 'public interface R_IResult<out T> : R_IResult'
    typeParameters:
    - id: T
    content.vb: >-
      Public Interface R_IResult(Of Out T)
          Inherits R_IResult
  inheritedMembers:
  - R_BlazorDeployment.R_IResult.Messages
  - R_BlazorDeployment.R_IResult.Succeeded
  extensionMethods:
  - System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  nameWithType.vb: R_IResult(Of T)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: R_BlazorDeployment.R_IResult(Of T)
  name.vb: R_IResult(Of T)
- uid: R_BlazorDeployment.R_IResult`1.Data
  commentId: P:R_BlazorDeployment.R_IResult`1.Data
  id: Data
  parent: R_BlazorDeployment.R_IResult`1
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: R_IResult<T>.Data
  fullName: R_BlazorDeployment.R_IResult<T>.Data
  type: Property
  source:
    remote:
      path: Library Back/R_BlazorDeployment/R_IResult.cs
      branch: master
      repo: git@github.com:siholsihol/RealtaNetCoreLibrary.git
    id: Data
    path: Library Back/R_BlazorDeployment/R_IResult.cs
    startLine: 12
  assemblies:
  - R_BlazorDeployment
  namespace: R_BlazorDeployment
  syntax:
    content: T Data { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: ReadOnly Property Data As T
  overload: R_BlazorDeployment.R_IResult`1.Data*
  nameWithType.vb: R_IResult(Of T).Data
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: R_BlazorDeployment.R_IResult(Of T).Data
references:
- uid: R_BlazorDeployment
  commentId: N:R_BlazorDeployment
  name: R_BlazorDeployment
  nameWithType: R_BlazorDeployment
  fullName: R_BlazorDeployment
- uid: R_BlazorDeployment.R_IResult.Messages
  commentId: P:R_BlazorDeployment.R_IResult.Messages
  parent: R_BlazorDeployment.R_IResult
  name: Messages
  nameWithType: R_IResult.Messages
  fullName: R_BlazorDeployment.R_IResult.Messages
- uid: R_BlazorDeployment.R_IResult.Succeeded
  commentId: P:R_BlazorDeployment.R_IResult.Succeeded
  parent: R_BlazorDeployment.R_IResult
  name: Succeeded
  nameWithType: R_IResult.Succeeded
  fullName: R_BlazorDeployment.R_IResult.Succeeded
- uid: System.Object.R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  parent: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  definition: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  name: ThrowIfNull()
  nameWithType: R_FrontExtensions.ThrowIfNull()
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull()
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorDeployment.R_IResult
  commentId: T:R_BlazorDeployment.R_IResult
  parent: R_BlazorDeployment
  name: R_IResult
  nameWithType: R_IResult
  fullName: R_BlazorDeployment.R_IResult
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  commentId: M:R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  isExternal: true
  name: ThrowIfNull(Object)
  nameWithType: R_FrontExtensions.ThrowIfNull(Object)
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
  spec.csharp:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull(System.Object)
    name: ThrowIfNull
    nameWithType: R_FrontExtensions.ThrowIfNull
    fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions.ThrowIfNull
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: R_BlazorFrontEnd.Extensions.R_FrontExtensions
  commentId: T:R_BlazorFrontEnd.Extensions.R_FrontExtensions
  parent: R_BlazorFrontEnd.Extensions
  name: R_FrontExtensions
  nameWithType: R_FrontExtensions
  fullName: R_BlazorFrontEnd.Extensions.R_FrontExtensions
- uid: R_BlazorFrontEnd.Extensions
  commentId: N:R_BlazorFrontEnd.Extensions
  name: R_BlazorFrontEnd.Extensions
  nameWithType: R_BlazorFrontEnd.Extensions
  fullName: R_BlazorFrontEnd.Extensions
- uid: R_BlazorDeployment.R_IResult`1.Data*
  commentId: Overload:R_BlazorDeployment.R_IResult`1.Data
  name: Data
  nameWithType: R_IResult<T>.Data
  fullName: R_BlazorDeployment.R_IResult<T>.Data
  nameWithType.vb: R_IResult(Of T).Data
  fullName.vb: R_BlazorDeployment.R_IResult(Of T).Data
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
