### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Deployment.Models
  commentId: N:R_BlazorFrontEnd.Deployment.Models
  id: R_BlazorFrontEnd.Deployment.Models
  children:
  - R_BlazorFrontEnd.Deployment.Models.AssemblyData
  - R_BlazorFrontEnd.Deployment.Models.Package
  langs:
  - csharp
  - vb
  name: R_BlazorFrontEnd.Deployment.Models
  nameWithType: R_BlazorFrontEnd.Deployment.Models
  fullName: R_BlazorFrontEnd.Deployment.Models
  type: Namespace
  assemblies:
  - R_BlazorFrontEnd
references:
- uid: R_BlazorFrontEnd.Deployment.Models.AssemblyData
  commentId: T:R_BlazorFrontEnd.Deployment.Models.AssemblyData
  parent: R_BlazorFrontEnd.Deployment.Models
  name: AssemblyData
  nameWithType: AssemblyData
  fullName: R_BlazorFrontEnd.Deployment.Models.AssemblyData
- uid: R_BlazorFrontEnd.Deployment.Models.Package
  commentId: T:R_BlazorFrontEnd.Deployment.Models.Package
  name: Package
  nameWithType: Package
  fullName: R_BlazorFrontEnd.Deployment.Models.Package
- uid: R_BlazorFrontEnd.Deployment.Models
  commentId: N:R_BlazorFrontEnd.Deployment.Models
  name: R_BlazorFrontEnd.Deployment.Models
  nameWithType: R_BlazorFrontEnd.Deployment.Models
  fullName: R_BlazorFrontEnd.Deployment.Models
