### YamlMime:ManagedReference
items:
- uid: R_BlazorFrontEnd.Deployment.Interfaces
  commentId: N:R_BlazorFrontEnd.Deployment.Interfaces
  id: R_BlazorFrontEnd.Deployment.Interfaces
  children:
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  - R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  langs:
  - csharp
  - vb
  name: R_BlazorFrontEnd.Deployment.Interfaces
  nameWithType: R_BlazorFrontEnd.Deployment.Interfaces
  fullName: R_BlazorFrontEnd.Deployment.Interfaces
  type: Namespace
  assemblies:
  - R_BlazorFrontEnd
references:
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
  name: R_IAssemblyDataProvider
  nameWithType: R_IAssemblyDataProvider
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyDataProvider
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
  name: R_IAssemblyLoadContext
  nameWithType: R_IAssemblyLoadContext
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IAssemblyLoadContext
- uid: R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  commentId: T:R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
  name: R_IDynamicAssetProviderService
  nameWithType: R_IDynamicAssetProviderService
  fullName: R_BlazorFrontEnd.Deployment.Interfaces.R_IDynamicAssetProviderService
